'use strict';

// Minecraft Java Edition 1.21.1 data registries
// Cross-checked against minecraft.wiki — do not edit without verifying against the wiki

// `category` + `order` drive grouped enchant dropdowns (e.g. give.html's optgroups):
// `category` is the group label, `order` is the global display position (1-42) that
// reproduces the curated UX ordering. This is a DIFFERENT axis from `applicableTo`
// (which item types can actually receive the enchant) — keep them separate.
const ENCHANTS = [
  { id: 'aqua_affinity',          name: 'Aqua Affinity',          maxLevel: 1,   category: 'Helmet',       order: 27, applicableTo: ['helmet'] },
  { id: 'bane_of_arthropods',     name: 'Bane of Arthropods',     maxLevel: 5,   category: 'Sword & Axe',  order: 3,  applicableTo: ['sword','axe'] },
  { id: 'binding_curse',          name: 'Curse of Binding',        maxLevel: 1,   category: 'Any Item',     order: 41, applicableTo: ['armor'] },
  { id: 'blast_protection',       name: 'Blast Protection',        maxLevel: 4,   category: 'Armor',        order: 30, applicableTo: ['armor'] },
  { id: 'breach',                 name: 'Breach',                  maxLevel: 4,   category: 'Mace',         order: 19, applicableTo: ['mace'] },
  { id: 'channeling',             name: 'Channeling',              maxLevel: 1,   category: 'Trident',      order: 18, applicableTo: ['trident'] },
  { id: 'density',                name: 'Density',                 maxLevel: 5,   category: 'Mace',         order: 20, applicableTo: ['mace'] },
  { id: 'depth_strider',          name: 'Depth Strider',           maxLevel: 3,   category: 'Boots',        order: 35, applicableTo: ['boots'] },
  { id: 'efficiency',             name: 'Efficiency',              maxLevel: 5,   category: 'Tools',        order: 22, applicableTo: ['pickaxe','shovel','axe','hoe','shears'] },
  { id: 'feather_falling',        name: 'Feather Falling',         maxLevel: 4,   category: 'Boots',        order: 34, applicableTo: ['boots'] },
  { id: 'fire_aspect',            name: 'Fire Aspect',             maxLevel: 2,   category: 'Sword & Axe',  order: 5,  applicableTo: ['sword'] },
  { id: 'fire_protection',        name: 'Fire Protection',         maxLevel: 4,   category: 'Armor',        order: 31, applicableTo: ['armor'] },
  { id: 'flame',                  name: 'Flame',                   maxLevel: 1,   category: 'Bow',          order: 10, applicableTo: ['bow'] },
  { id: 'fortune',                name: 'Fortune',                 maxLevel: 3,   category: 'Tools',        order: 24, applicableTo: ['pickaxe','shovel','axe','hoe'] },
  { id: 'frost_walker',           name: 'Frost Walker',            maxLevel: 2,   category: 'Boots',        order: 36, applicableTo: ['boots'] },
  { id: 'impaling',               name: 'Impaling',                maxLevel: 5,   category: 'Trident',      order: 16, applicableTo: ['trident'] },
  { id: 'infinity',               name: 'Infinity',                maxLevel: 1,   category: 'Bow',          order: 11, applicableTo: ['bow'] },
  { id: 'knockback',              name: 'Knockback',               maxLevel: 2,   category: 'Sword & Axe',  order: 4,  applicableTo: ['sword'] },
  { id: 'looting',                name: 'Looting',                 maxLevel: 3,   category: 'Sword & Axe',  order: 6,  applicableTo: ['sword'] },
  { id: 'loyalty',                name: 'Loyalty',                 maxLevel: 3,   category: 'Trident',      order: 17, applicableTo: ['trident'] },
  { id: 'luck_of_the_sea',        name: 'Luck of the Sea',         maxLevel: 3,   category: 'Tools',        order: 25, applicableTo: ['fishing_rod'] },
  { id: 'lure',                   name: 'Lure',                    maxLevel: 3,   category: 'Tools',        order: 26, applicableTo: ['fishing_rod'] },
  { id: 'mending',                name: 'Mending',                 maxLevel: 1,   category: 'Any Item',     order: 40, applicableTo: ['any'] },
  { id: 'multishot',              name: 'Multishot',               maxLevel: 1,   category: 'Crossbow',     order: 12, applicableTo: ['crossbow'] },
  { id: 'piercing',               name: 'Piercing',                maxLevel: 4,   category: 'Crossbow',     order: 13, applicableTo: ['crossbow'] },
  { id: 'power',                  name: 'Power',                   maxLevel: 5,   category: 'Bow',          order: 8,  applicableTo: ['bow'] },
  { id: 'projectile_protection',  name: 'Projectile Protection',   maxLevel: 4,   category: 'Armor',        order: 32, applicableTo: ['armor'] },
  { id: 'protection',             name: 'Protection',              maxLevel: 4,   category: 'Armor',        order: 29, applicableTo: ['armor'] },
  { id: 'punch',                  name: 'Punch',                   maxLevel: 2,   category: 'Bow',          order: 9,  applicableTo: ['bow'] },
  { id: 'quick_charge',           name: 'Quick Charge',            maxLevel: 3,   category: 'Crossbow',     order: 14, applicableTo: ['crossbow'] },
  { id: 'respiration',            name: 'Respiration',             maxLevel: 3,   category: 'Helmet',       order: 28, applicableTo: ['helmet'] },
  { id: 'riptide',                name: 'Riptide',                 maxLevel: 3,   category: 'Trident',      order: 15, applicableTo: ['trident'] },
  { id: 'sharpness',              name: 'Sharpness',               maxLevel: 5,   category: 'Sword & Axe',  order: 1,  applicableTo: ['sword','axe'] },
  { id: 'silk_touch',             name: 'Silk Touch',              maxLevel: 1,   category: 'Tools',        order: 23, applicableTo: ['pickaxe','shovel','axe','hoe','shears'] },
  { id: 'smite',                  name: 'Smite',                   maxLevel: 5,   category: 'Sword & Axe',  order: 2,  applicableTo: ['sword','axe'] },
  { id: 'soul_speed',             name: 'Soul Speed',              maxLevel: 3,   category: 'Boots',        order: 37, applicableTo: ['boots'] },
  { id: 'sweeping_edge',          name: 'Sweeping Edge',           maxLevel: 3,   category: 'Sword & Axe',  order: 7,  applicableTo: ['sword'] },
  { id: 'swift_sneak',            name: 'Swift Sneak',             maxLevel: 3,   category: 'Leggings',     order: 38, applicableTo: ['leggings'] },
  { id: 'thorns',                 name: 'Thorns',                  maxLevel: 3,   category: 'Armor',        order: 33, applicableTo: ['armor'] },
  { id: 'unbreaking',             name: 'Unbreaking',              maxLevel: 3,   category: 'Any Item',     order: 39, applicableTo: ['any'] },
  { id: 'vanishing_curse',        name: 'Curse of Vanishing',      maxLevel: 1,   category: 'Any Item',     order: 42, applicableTo: ['any'] },
  { id: 'wind_burst',             name: 'Wind Burst',              maxLevel: 3,   category: 'Mace',         order: 21, applicableTo: ['mace'] },
].sort((a, b) => a.id.localeCompare(b.id));

const EFFECTS = [
  { id: 'absorption',          name: 'Absorption',          color: '#2552a5' },
  { id: 'bad_omen',            name: 'Bad Omen',             color: '#0b6138' },
  { id: 'blindness',           name: 'Blindness',            color: '#1f1f23' },
  { id: 'conduit_power',       name: 'Conduit Power',        color: '#1dc2d4' },
  { id: 'darkness',            name: 'Darkness',             color: '#292721' },
  { id: 'dolphins_grace',      name: "Dolphin's Grace",      color: '#88ade0' },
  { id: 'fire_resistance',     name: 'Fire Resistance',      color: '#e49a3a' },
  { id: 'glowing',             name: 'Glowing',              color: '#94a061' },
  { id: 'haste',               name: 'Haste',                color: '#d9c043' },
  { id: 'health_boost',        name: 'Health Boost',         color: '#f87d23' },
  { id: 'hero_of_the_village', name: 'Hero of the Village',  color: '#44ff44' },
  { id: 'hunger',              name: 'Hunger',               color: '#587653' },
  { id: 'infested',            name: 'Infested',             color: '#9a9a9a' },
  { id: 'instant_damage',      name: 'Instant Damage',       color: '#430a09' },
  { id: 'instant_health',      name: 'Instant Health',       color: '#f82423' },
  { id: 'invisibility',        name: 'Invisibility',         color: '#7f8392' },
  { id: 'jump_boost',          name: 'Jump Boost',           color: '#786297' },
  { id: 'levitation',          name: 'Levitation',           color: '#ceffff' },
  { id: 'luck',                name: 'Luck',                 color: '#339900' },
  { id: 'mining_fatigue',      name: 'Mining Fatigue',       color: '#4a4217' },
  { id: 'nausea',              name: 'Nausea',               color: '#551d4a' },
  { id: 'night_vision',        name: 'Night Vision',         color: '#1f1fa1' },
  { id: 'oozing',              name: 'Oozing',               color: '#7fbd30' },
  { id: 'poison',              name: 'Poison',               color: '#4e9331' },
  { id: 'raid_omen',           name: 'Raid Omen',            color: '#0b6138' },
  { id: 'regeneration',        name: 'Regeneration',         color: '#cd5cab' },
  { id: 'resistance',          name: 'Resistance',           color: '#99453a' },
  { id: 'saturation',          name: 'Saturation',           color: '#f82423' },
  { id: 'slowness',            name: 'Slowness',             color: '#5a6c81' },
  { id: 'slow_falling',        name: 'Slow Falling',         color: '#f7f8e0' },
  { id: 'speed',               name: 'Speed',                color: '#7cafc2' },
  { id: 'strength',            name: 'Strength',             color: '#932423' },
  { id: 'trial_omen',          name: 'Trial Omen',           color: '#0b6138' },
  { id: 'unluck',              name: 'Unluck',               color: '#84a17d' },
  { id: 'water_breathing',     name: 'Water Breathing',      color: '#2e5299' },
  { id: 'weakness',            name: 'Weakness',             color: '#484d48' },
  { id: 'weaving',             name: 'Weaving',              color: '#a07090' },
  { id: 'wind_charged',        name: 'Wind Charged',         color: '#aaeeff' },
  { id: 'wither',              name: 'Wither',               color: '#352a27' },
].sort((a, b) => a.id.localeCompare(b.id));

const ATTRIBUTES = [
  { id: 'generic.armor',                      displayName: 'Armor' },
  { id: 'generic.armor_toughness',            displayName: 'Armor Toughness' },
  { id: 'generic.attack_damage',              displayName: 'Attack Damage' },
  { id: 'generic.attack_knockback',           displayName: 'Attack Knockback' },
  { id: 'generic.attack_speed',               displayName: 'Attack Speed' },
  { id: 'generic.block_break_speed',          displayName: 'Block Break Speed' },
  { id: 'generic.block_interaction_range',    displayName: 'Block Interaction Range' },
  { id: 'generic.burning_time',               displayName: 'Burning Time' },
  { id: 'generic.entity_interaction_range',   displayName: 'Entity Interaction Range' },
  { id: 'generic.explosion_knockback_resistance', displayName: 'Explosion Knockback Resistance' },
  { id: 'generic.fall_damage_multiplier',     displayName: 'Fall Damage Multiplier' },
  { id: 'generic.flying_speed',               displayName: 'Flying Speed' },
  { id: 'generic.follow_range',               displayName: 'Follow Range' },
  { id: 'generic.gravity',                    displayName: 'Gravity' },
  { id: 'generic.jump_strength',              displayName: 'Jump Strength' },
  { id: 'generic.knockback_resistance',       displayName: 'Knockback Resistance' },
  { id: 'generic.luck',                       displayName: 'Luck' },
  { id: 'generic.max_absorption',             displayName: 'Max Absorption' },
  { id: 'generic.max_health',                 displayName: 'Max Health' },
  { id: 'generic.mining_efficiency',          displayName: 'Mining Efficiency' },
  { id: 'generic.movement_efficiency',        displayName: 'Movement Efficiency' },
  { id: 'generic.movement_speed',             displayName: 'Movement Speed' },
  { id: 'generic.oxygen_bonus',               displayName: 'Oxygen Bonus' },
  { id: 'generic.safe_fall_distance',         displayName: 'Safe Fall Distance' },
  { id: 'generic.scale',                      displayName: 'Scale' },
  { id: 'generic.step_height',                displayName: 'Step Height' },
  { id: 'generic.submerged_mining_speed',     displayName: 'Submerged Mining Speed' },
  { id: 'generic.sweeping_damage_ratio',      displayName: 'Sweeping Damage Ratio' },
  { id: 'generic.water_movement_efficiency',  displayName: 'Water Movement Efficiency' },
  { id: 'player.block_break_speed',           displayName: 'Block Break Speed (Player)' },
  { id: 'player.block_interaction_range',     displayName: 'Block Interaction Range (Player)' },
  { id: 'player.entity_interaction_range',    displayName: 'Entity Interaction Range (Player)' },
  { id: 'zombie.spawn_reinforcements',        displayName: 'Spawn Reinforcements (Zombie)' },
];

const SLOTS = ['mainhand', 'offhand', 'hand', 'head', 'chest', 'legs', 'feet', 'armor', 'body', 'any'];

const OPERATIONS = [
  { id: 'add_value',            label: 'add_value' },
  { id: 'add_multiplied_base',  label: '× base' },
  { id: 'add_multiplied_total', label: '× total' },
];

const ENTITIES = [
  // Hostile
  { id: 'blaze',              name: 'Blaze',              category: 'hostile' },
  { id: 'bogged',             name: 'Bogged',             category: 'hostile' },
  { id: 'breeze',             name: 'Breeze',             category: 'hostile' },
  { id: 'cave_spider',        name: 'Cave Spider',        category: 'hostile' },
  { id: 'creeper',            name: 'Creeper',            category: 'hostile' },
  { id: 'drowned',            name: 'Drowned',            category: 'hostile' },
  { id: 'elder_guardian',     name: 'Elder Guardian',     category: 'hostile' },
  { id: 'endermite',          name: 'Endermite',          category: 'hostile' },
  { id: 'evoker',             name: 'Evoker',             category: 'hostile' },
  { id: 'ghast',              name: 'Ghast',              category: 'hostile' },
  { id: 'guardian',           name: 'Guardian',           category: 'hostile' },
  { id: 'hoglin',             name: 'Hoglin',             category: 'hostile' },
  { id: 'husk',               name: 'Husk',               category: 'hostile' },
  { id: 'magma_cube',         name: 'Magma Cube',         category: 'hostile' },
  { id: 'phantom',            name: 'Phantom',            category: 'hostile' },
  { id: 'piglin',             name: 'Piglin',             category: 'hostile' },
  { id: 'piglin_brute',       name: 'Piglin Brute',       category: 'hostile' },
  { id: 'pillager',           name: 'Pillager',           category: 'hostile' },
  { id: 'ravager',            name: 'Ravager',            category: 'hostile' },
  { id: 'shulker',            name: 'Shulker',            category: 'hostile' },
  { id: 'silverfish',         name: 'Silverfish',         category: 'hostile' },
  { id: 'skeleton',           name: 'Skeleton',           category: 'hostile' },
  { id: 'slime',              name: 'Slime',              category: 'hostile' },
  { id: 'spider',             name: 'Spider',             category: 'hostile' },
  { id: 'stray',              name: 'Stray',              category: 'hostile' },
  { id: 'vex',                name: 'Vex',                category: 'hostile' },
  { id: 'vindicator',         name: 'Vindicator',         category: 'hostile' },
  { id: 'witch',              name: 'Witch',              category: 'hostile' },
  { id: 'wither_skeleton',    name: 'Wither Skeleton',    category: 'hostile' },
  { id: 'zoglin',             name: 'Zoglin',             category: 'hostile' },
  { id: 'zombie',             name: 'Zombie',             category: 'hostile' },
  { id: 'zombie_villager',    name: 'Zombie Villager',    category: 'hostile' },
  { id: 'zombified_piglin',   name: 'Zombified Piglin',   category: 'hostile' },
  // Passive
  { id: 'allay',              name: 'Allay',              category: 'passive' },
  { id: 'armadillo',          name: 'Armadillo',          category: 'passive' },
  { id: 'axolotl',            name: 'Axolotl',            category: 'passive' },
  { id: 'bat',                name: 'Bat',                category: 'passive' },
  { id: 'bee',                name: 'Bee',                category: 'passive' },
  { id: 'camel',              name: 'Camel',              category: 'passive' },
  { id: 'cat',                name: 'Cat',                category: 'passive' },
  { id: 'chicken',            name: 'Chicken',            category: 'passive' },
  { id: 'cod',                name: 'Cod',                category: 'passive' },
  { id: 'cow',                name: 'Cow',                category: 'passive' },
  { id: 'donkey',             name: 'Donkey',             category: 'passive' },
  { id: 'frog',               name: 'Frog',               category: 'passive' },
  { id: 'glow_squid',         name: 'Glow Squid',         category: 'passive' },
  { id: 'goat',               name: 'Goat',               category: 'passive' },
  { id: 'horse',              name: 'Horse',              category: 'passive' },
  { id: 'llama',              name: 'Llama',              category: 'passive' },
  { id: 'mooshroom',          name: 'Mooshroom',          category: 'passive' },
  { id: 'mule',               name: 'Mule',               category: 'passive' },
  { id: 'ocelot',             name: 'Ocelot',             category: 'passive' },
  { id: 'panda',              name: 'Panda',              category: 'passive' },
  { id: 'parrot',             name: 'Parrot',             category: 'passive' },
  { id: 'pig',                name: 'Pig',                category: 'passive' },
  { id: 'polar_bear',         name: 'Polar Bear',         category: 'passive' },
  { id: 'pufferfish',         name: 'Pufferfish',         category: 'passive' },
  { id: 'rabbit',             name: 'Rabbit',             category: 'passive' },
  { id: 'salmon',             name: 'Salmon',             category: 'passive' },
  { id: 'sheep',              name: 'Sheep',              category: 'passive' },
  { id: 'sniffer',            name: 'Sniffer',            category: 'passive' },
  { id: 'snow_golem',         name: 'Snow Golem',         category: 'passive' },
  { id: 'squid',              name: 'Squid',              category: 'passive' },
  { id: 'strider',            name: 'Strider',            category: 'passive' },
  { id: 'tadpole',            name: 'Tadpole',            category: 'passive' },
  { id: 'trader_llama',       name: 'Trader Llama',       category: 'passive' },
  { id: 'tropical_fish',      name: 'Tropical Fish',      category: 'passive' },
  { id: 'turtle',             name: 'Turtle',             category: 'passive' },
  { id: 'villager',           name: 'Villager',           category: 'passive' },
  { id: 'wandering_trader',   name: 'Wandering Trader',   category: 'passive' },
  { id: 'wolf',               name: 'Wolf',               category: 'passive' },
  // Boss
  { id: 'ender_dragon',       name: 'Ender Dragon',       category: 'boss' },
  { id: 'iron_golem',         name: 'Iron Golem',         category: 'boss' },
  { id: 'warden',             name: 'Warden',             category: 'boss' },
  { id: 'wither',             name: 'Wither',             category: 'boss' },
  // Misc
  { id: 'armor_stand',        name: 'Armor Stand',        category: 'misc' },
  { id: 'boat',               name: 'Boat',               category: 'misc' },
  { id: 'chest_boat',         name: 'Chest Boat',         category: 'misc' },
  { id: 'chest_minecart',     name: 'Chest Minecart',     category: 'misc' },
  { id: 'command_block_minecart', name: 'Command Block Minecart', category: 'misc' },
  { id: 'enderman',           name: 'Enderman',           category: 'misc' },
  { id: 'experience_orb',     name: 'Experience Orb',     category: 'misc' },
  { id: 'falling_block',      name: 'Falling Block',      category: 'misc' },
  { id: 'fireball',           name: 'Fireball',           category: 'misc' },
  { id: 'firework_rocket',    name: 'Firework Rocket',    category: 'misc' },
  { id: 'furnace_minecart',   name: 'Furnace Minecart',   category: 'misc' },
  { id: 'hopper_minecart',    name: 'Hopper Minecart',    category: 'misc' },
  { id: 'item',               name: 'Item',               category: 'misc' },
  { id: 'item_display',       name: 'Item Display',       category: 'misc' },
  { id: 'item_frame',         name: 'Item Frame',         category: 'misc' },
  { id: 'minecart',           name: 'Minecart',           category: 'misc' },
  { id: 'painting',           name: 'Painting',           category: 'misc' },
  { id: 'tnt',                name: 'TNT',                category: 'misc' },
  { id: 'tnt_minecart',       name: 'TNT Minecart',       category: 'misc' },
  { id: 'wind_charge',        name: 'Wind Charge',        category: 'misc' },
  { id: 'zombie_horse',       name: 'Zombie Horse',       category: 'misc' },
  { id: 'skeleton_horse',     name: 'Skeleton Horse',     category: 'misc' },
];

const PARTICLES = [
  { id: 'ambient_entity_effect',  extraData: false },
  { id: 'angry_villager',         extraData: false },
  { id: 'ash',                    extraData: false },
  { id: 'block',                  extraData: true  },
  { id: 'block_crumble',          extraData: true  },
  { id: 'block_marker',           extraData: true  },
  { id: 'bubble',                 extraData: false },
  { id: 'bubble_column_up',       extraData: false },
  { id: 'bubble_pop',             extraData: false },
  { id: 'campfire_cosy_smoke',    extraData: false },
  { id: 'campfire_signal_smoke',  extraData: false },
  { id: 'cherry_leaves',          extraData: false },
  { id: 'cloud',                  extraData: false },
  { id: 'composter',              extraData: false },
  { id: 'crimson_spore',          extraData: false },
  { id: 'crit',                   extraData: false },
  { id: 'current_down',           extraData: false },
  { id: 'damage_indicator',       extraData: false },
  { id: 'dolphin',                extraData: false },
  { id: 'dragon_breath',          extraData: false },
  { id: 'dripping_dripstone_lava',extraData: false },
  { id: 'dripping_dripstone_water',extraData: false },
  { id: 'dripping_honey',         extraData: false },
  { id: 'dripping_lava',          extraData: false },
  { id: 'dripping_obsidian_tear', extraData: false },
  { id: 'dripping_water',         extraData: false },
  { id: 'dust',                   extraData: true  },
  { id: 'dust_color_transition',  extraData: true  },
  { id: 'dust_pillar',            extraData: true  },
  { id: 'dust_plume',             extraData: false },
  { id: 'egg_crack',              extraData: false },
  { id: 'elder_guardian',         extraData: false },
  { id: 'electric_spark',         extraData: false },
  { id: 'enchant',                extraData: false },
  { id: 'enchanted_hit',          extraData: false },
  { id: 'end_rod',                extraData: false },
  { id: 'entity_effect',          extraData: true  },
  { id: 'explosion',              extraData: false },
  { id: 'explosion_emitter',      extraData: false },
  { id: 'falling_dripstone_lava', extraData: false },
  { id: 'falling_dripstone_water',extraData: false },
  { id: 'falling_dust',           extraData: true  },
  { id: 'falling_honey',          extraData: false },
  { id: 'falling_lava',           extraData: false },
  { id: 'falling_nectar',         extraData: false },
  { id: 'falling_obsidian_tear',  extraData: false },
  { id: 'falling_spore_blossom',  extraData: false },
  { id: 'falling_water',          extraData: false },
  { id: 'firefly',                extraData: false },
  { id: 'firework',               extraData: false },
  { id: 'fishing',                extraData: false },
  { id: 'flame',                  extraData: false },
  { id: 'flash',                  extraData: false },
  { id: 'glow',                   extraData: false },
  { id: 'glow_squid_ink',         extraData: false },
  { id: 'gust',                   extraData: false },
  { id: 'gust_emitter_large',     extraData: false },
  { id: 'gust_emitter_small',     extraData: false },
  { id: 'happy_villager',         extraData: false },
  { id: 'heart',                  extraData: false },
  { id: 'infested',               extraData: false },
  { id: 'instant_effect',         extraData: false },
  { id: 'item',                   extraData: true  },
  { id: 'item_slime',             extraData: false },
  { id: 'item_cobweb',            extraData: false },
  { id: 'item_snowball',          extraData: false },
  { id: 'landing_honey',          extraData: false },
  { id: 'landing_lava',           extraData: false },
  { id: 'landing_obsidian_tear',  extraData: false },
  { id: 'large_smoke',            extraData: false },
  { id: 'lava',                   extraData: false },
  { id: 'mycelium',               extraData: false },
  { id: 'nautilus',               extraData: false },
  { id: 'note',                   extraData: false },
  { id: 'ominous_spawning',       extraData: false },
  { id: 'poof',                   extraData: false },
  { id: 'portal',                 extraData: false },
  { id: 'raid_omen',              extraData: false },
  { id: 'rain',                   extraData: false },
  { id: 'reverse_portal',         extraData: false },
  { id: 'scrape',                 extraData: false },
  { id: 'sculk_charge',           extraData: true  },
  { id: 'sculk_charge_pop',       extraData: false },
  { id: 'sculk_soul',             extraData: false },
  { id: 'shriek',                 extraData: true  },
  { id: 'small_flame',            extraData: false },
  { id: 'small_gust',             extraData: false },
  { id: 'smoke',                  extraData: false },
  { id: 'sneeze',                 extraData: false },
  { id: 'snowflake',              extraData: false },
  { id: 'sonic_boom',             extraData: false },
  { id: 'soul',                   extraData: false },
  { id: 'soul_fire_flame',        extraData: false },
  { id: 'spit',                   extraData: false },
  { id: 'splash',                 extraData: false },
  { id: 'spore_blossom_air',      extraData: false },
  { id: 'squid_ink',              extraData: false },
  { id: 'sweep_attack',           extraData: false },
  { id: 'tinted_leaves',          extraData: false },
  { id: 'totem_of_undying',       extraData: false },
  { id: 'trial_omen',             extraData: false },
  { id: 'trial_spawner_detection',extraData: false },
  { id: 'trial_spawner_detection_ominous', extraData: false },
  { id: 'underwater',             extraData: false },
  { id: 'vault_connection',       extraData: false },
  { id: 'vibration',              extraData: true  },
  { id: 'warped_spore',           extraData: false },
  { id: 'wax_off',                extraData: false },
  { id: 'wax_on',                 extraData: false },
  { id: 'white_ash',              extraData: false },
  { id: 'white_smoke',            extraData: false },
  { id: 'witch',                  extraData: false },
].sort((a, b) => a.id.localeCompare(b.id));

const VILLAGER_PROFESSIONS = [
  'armorer','butcher','cartographer','cleric','farmer','fisherman',
  'fletcher','leatherworker','librarian','mason','nitwit','none',
  'shepherd','toolsmith','weaponsmith',
];

const VILLAGER_BIOMES = [
  'desert','jungle','plains','savanna','snow','swamp','taiga',
];

const BIOMES = [
  'badlands','bamboo_jungle','basalt_deltas','beach','birch_forest','cherry_grove',
  'cold_ocean','crimson_forest','dark_forest','deep_cold_ocean','deep_dark',
  'deep_frozen_ocean','deep_lukewarm_ocean','deep_ocean','desert','dripstone_caves',
  'end_barrens','end_highlands','end_midlands','eroded_badlands','flower_forest',
  'forest','frozen_ocean','frozen_peaks','frozen_river','grove','ice_spikes',
  'jagged_peaks','jungle','lukewarm_ocean','lush_caves','mangrove_swamp',
  'meadow','mushroom_fields','nether_wastes','ocean','old_growth_birch_forest',
  'old_growth_pine_taiga','old_growth_spruce_taiga','plains','river','savanna',
  'savanna_plateau','small_end_islands','snowy_beach','snowy_plains','snowy_slopes',
  'snowy_taiga','soul_sand_valley','sparse_jungle','stony_peaks','stony_shore',
  'sunflower_plains','swamp','taiga','the_end','the_void','warm_ocean',
  'warped_forest','windswept_forest','windswept_gravelly_hills','windswept_hills',
  'windswept_savanna','wooded_badlands',
];
